#!/usr/bin/env python
"""
Demo script showing how to use the scheduled screenshot monitor.

This is a simplified demonstration that shows the basic usage pattern.
For full functionality, run the actual scheduled_screenshot_monitor.py script.
"""

import asyncio
import sys
import os

# Ensure the project root is in the path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

print('=' * 70)
print('Scheduled Screenshot Monitor - Usage Demonstration')
print('=' * 70)
print()
print('This tool provides automated screenshot monitoring for websites.')
print()
print('KEY FEATURES:')
print('  ✓ Wait for manual login (supports captcha)')
print('  ✓ AI-powered chart/dashboard block identification')
print('  ✓ Periodic screenshot capture')
print('  ✓ Metadata recording (timestamp, block name, file path)')
print()
print('=' * 70)
print('BASIC USAGE:')
print('=' * 70)
print()
print('  python examples/use-cases/scheduled_screenshot_monitor.py \\')
print('      --url "https://your-dashboard.com" \\')
print('      --interval 300')
print()
print('=' * 70)
print('PARAMETERS:')
print('=' * 70)
print()
print('  --url URL              Target website URL (required)')
print('  --interval SECONDS     Screenshot interval in seconds (default: 300)')
print('  --screenshot-dir DIR   Screenshot directory (default: screenshots)')
print('  --metadata-file FILE   Metadata JSON file (default: screenshot_metadata.json)')
print()
print('=' * 70)
print('EXAMPLE SCENARIOS:')
print('=' * 70)
print()
print('1. Monitor every 5 minutes (300 seconds):')
print('   python examples/use-cases/scheduled_screenshot_monitor.py \\')
print('       --url "https://dashboard.example.com" \\')
print('       --interval 300')
print()
print('2. Monitor every 1 hour (3600 seconds):')
print('   python examples/use-cases/scheduled_screenshot_monitor.py \\')
print('       --url "https://analytics.example.com" \\')
print('       --interval 3600')
print()
print('3. Custom output directory:')
print('   python examples/use-cases/scheduled_screenshot_monitor.py \\')
print('       --url "https://metrics.example.com" \\')
print('       --interval 600 \\')
print('       --screenshot-dir "my_screenshots" \\')
print('       --metadata-file "my_metadata.json"')
print()
print('=' * 70)
print('WORKFLOW:')
print('=' * 70)
print()
print('1. 🔐 Login Phase:')
print('   - Browser opens to target URL')
print('   - User manually logs in (handles username, password, captcha)')
print('   - User presses ENTER when login is complete')
print()
print('2. 🔍 Identification Phase:')
print('   - AI analyzes page structure')
print('   - Identifies chart blocks and dashboard sections')
print('   - Generates CSS selectors for each block')
print()
print('3. 📸 Monitoring Phase:')
print('   - Periodic screenshot capture at configured interval')
print('   - Each block is screenshotted separately')
print('   - Screenshots saved with descriptive names')
print('   - Metadata recorded in JSON format')
print()
print('=' * 70)
print('OUTPUT EXAMPLE:')
print('=' * 70)
print()
print('Screenshots:')
print('  screenshots/Sales-Chart_20260108_120000.png')
print('  screenshots/Revenue-Graph_20260108_120000.png')
print('  screenshots/Performance-Dashboard_20260108_120000.png')
print()
print('Metadata (screenshot_metadata.json):')
print('  [')
print('    {')
print('      "timestamp": "2026-01-08T12:00:00.123456",')
print('      "block_name": "Sales-Chart",')
print('      "screenshot_path": "screenshots/Sales-Chart_20260108_120000.png",')
print('      "url": "https://dashboard.example.com"')
print('    },')
print('    ...')
print('  ]')
print()
print('=' * 70)
print('REQUIREMENTS:')
print('=' * 70)
print()
print('  1. Install browser-use:')
print('     uv add browser-use')
print()
print('  2. Install browser:')
print('     uvx browser-use install')
print()
print('  3. Set LLM API key in .env file:')
print('     BROWSER_USE_API_KEY=your-key  # or OPENAI_API_KEY, etc.')
print()
print('=' * 70)
print('DOCUMENTATION:')
print('=' * 70)
print()
print('For detailed Chinese documentation, see:')
print('  examples/use-cases/SCHEDULED_SCREENSHOT_README.md')
print()
print('=' * 70)
print()
